apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments-ms
  name: payments-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments-ms
    spec:
      containers:
        - image: southamerica-east1-docker.pkg.dev/products-app-microservices/image-registry/payments-ms
          name: payments-ms
          resources: {}
          env:
            - name: PORT
              value: "3000"
            - name: NATS_SERVERS
              value: nats://nats:4222
            - name: STRIPE_SUCCESS_URL
              value: "http://localhost:3003/payments/success"
            - name: STRIPE_CANCEL_URL
              value: "http://localhost:3003/payments/cancelled"
            - name: STRIPE_SECRET
              valueFrom:
                secretKeyRef:
                  name: payments-ms-secrets
                  key: stripe_secret
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: payments-ms-secrets
                  key: stripe_webhook_secret
status: {}
