apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: products-ms
  name: products-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: products-ms
    spec:
      containers:
        - image: southamerica-east1-docker.pkg.dev/products-app-microservices/image-registry/products-ms
          name: products-ms
          resources: {}
          env:
            - name: PORT
              value: "3000"
            - name: NATS_SERVERS
              value: nats://nats:4222
            - name: DATABASE_URL
              value: file:./dev.db
status: {}
